services:

  redis:
    image: redis:latest
    container_name: redis_burung_cache
    ports:
      - "6379:6379"
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_burung_message_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: burung_user
      RABBITMQ_DEFAULT_PASS: burung_pass
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions_vhost_rmq.json
    volumes:
      - ./definitions_vhost_rmq.json:/etc/rabbitmq/definitions_vhost_rmq.json:ro
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch_burung_search_engine
    environment:
      MEILI_MASTER_KEY: "SuperSecureKey123456"
    ports:
      - "7700:7700"
    restart: unless-stopped

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_burung_hystorical_data
    environment:
      - CASSANDRA_CLUSTER_NAME=burung_cluster
      - CASSANDRA_NUM_TOKENS=8
    ports:
      - "9042:9042"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio_burung_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: burung_app
      MINIO_ROOT_PASSWORD: burung_app123
    ports:
      - "9000:9000"   # API S3 compatible
      - "9001:9001"   # MinIO console UI
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:
